spring:
  application:
    name: infrastructure
  tenant-datasource:
    minimum-idle: 2
    maximum-pool-size: 10
    connection-timeout: 150000
    idle-timeout: 150000
    initialization-fail-timeout: 150000
  jpa:
    properties:
      hibernate:
        cache:
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          use_second_level_cache: true
          use_query_cache: false
          keys_factory: com.infrastructure.config.jpa.TenantAwareCacheKeysFactory
          provider_configuration_file_resource_path: hibernate-redis.properties
          multiTenancy: DATABASE
        show_sql: true
        format_sql: true

jwt:
  secretKey: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwMDYzODUzNywiaWF0IjoxNzAwNjM4NTM3fQ.cakxNusKVbUYfXIO_ldis-uQtQMxRO58Tktr31X6O_I
  expirationMinutes: 60

corsConfig:
  allowedOrigin: http://localhost:${server.port}

springdoc:
  swagger-ui:
    persistAuthorization: true
    server-url: http://localhost:${server.port}
    path: /swagger-ui/index.html
    enabled: true
    disable-swagger-default-url: true


